// 유물 데이터
const RELIC_DATA = [
    // 레이드 1단계
    { id: 'aegis', name: '아이기스', tier: '레이드 1단계', blackhammerTier: 1,
      baseStat: [['방어력', 1], ['체력', 40]],
      ability: '피격시 {4}% 확률로 적이 기절하고 자신의 체력 {40} 회복, 파이터가 장착 시 막기의 무적 지속시간 +{0.2}초',
      abilityStart: 5 },
    { id: 'achilles', name: '아킬레우스갑주', tier: '레이드 1단계', blackhammerTier: 1,
      baseStat: [['체력', 80]],
      ability: '2천(고정) 이상의 피해를 입으면 피해량 {3}% 감소, 팔라딘이 장착 시 신성력 최대량 {20}% 증가',
      abilityStart: 5 },
    { id: 'durandal', name: '듀랜달', tier: '레이드 1단계', blackhammerTier: 1,
      baseStat: [['공격력', 2], ['경험치획득률', 1, '%']],
      ability: '크리티컬 데미지가 {3}% 증가, 서모너가 장착 시 4초(고정)마다 서모닝소드 {0.5}기 자동 충전',
      abilityStart: 5 },
    { id: 'failnot', name: '페일노트', tier: '레이드 1단계', blackhammerTier: 1,
      baseStat: [['공격속도', 2.5, '%']],
      ability: '아쳐가 착용 시 {3}% 확률로 공격력 25%(고정)의 추가 멀티샷, 거너가 장착 후 공격 시 {2}% 확률로 탄환 즉시 장착',
      abilityStart: 5 },
    { id: 'mjolnir', name: '묠니르', tier: '레이드 1단계', blackhammerTier: 1,
      baseStat: [['공격력', 3], ['크리티컬확률', 1, '%']],
      ability: '전격의명검 전기데미지 {20}% 상승, 해머러가 장착 시 그레이트해머 지속시간 {0.5}초 증가',
      abilityStart: 5 },

    // 레이드 2단계
    { id: 'hildegrim', name: '힐데그림', tier: '레이드 2단계', blackhammerTier: 1,
      baseStat: [['경험치획득률', 3, '%']],
      ability: '피격시 경험치 {0.5} 증가, 페인터 장착 시 모든 혼합 스킬 데미지 {20}% 증가',
      abilityStart: 5 },
    { id: 'dragoncrest', name: '청룡언월도', tier: '레이드 2단계', blackhammerTier: 1,
      baseStat: [['공격속도', 2, '%']],
      ability: '버서커가 장착 후 공격 시 {4}% 확률로 전방에 공격력 40%(고정)의 검기 발동, 사무라이가 장착 시 검기 확률 {3}% 증가',
      abilityStart: 5 },
    { id: 'ruyi', name: '여의봉', tier: '레이드 2단계', blackhammerTier: 2,
      baseStat: [['크리티컬확률', 2, '%']],
      ability: '매지션이 장착 시 기본공격 및 다크스피어 사거리 {13}% 증가, 거너가 장착 시 기본 사거리 {4}% 증가, 메카닉이 장착 시 자동공격 사거리 {20}% 증가',
      abilityStart: 5 },
    { id: 'caladbolg', name: '칼라드블그', tier: '레이드 2단계', blackhammerTier: 2,
      baseStat: [['공격속도', 1, '%'], ['방어력', 1]],
      ability: '나이트, 피에로, 가디언, 해머러, 팔라딘이 장착 시 총 방어력 {3}% 증가',
      abilityStart: 5 },
    { id: 'daitsuren', name: '다이츠렌', tier: '레이드 2단계', blackhammerTier: 2,
      baseStat: [['흡혈', 0.4, '%']],
      ability: '쉐프가 장착 시 패시브 최대 스택 {100} 증가, 네크로맨서가 장착 시 영혼 최대 스택 {1} 증가, 블레이드가 장착 시 기력 최대 스택 {10}% 증가',
      abilityStart: 5 },

    // 레이드 3단계
    { id: 'galatine', name: '갈라틴', tier: '레이드 3단계', blackhammerTier: 2,
      baseStat: [['공격력', 3]],
      ability: '근접 영웅이 장착 시 현재 웨이브x{1} 만큼 공격력 증가, 비스트가 장착 시 2배(고정) 적용',
      abilityStart: 5 },
    { id: 'plumblossom', name: '매화검', tier: '레이드 3단계', blackhammerTier: 2,
      baseStat: [['공격속도', 3, '%']],
      ability: '머스킷티어가 저격 사용시 다음 저격 데미지 {2}% 증가(최대 50%(고정) 누적), 사무라이가 장착 후 콤보 성공 시 {13}%로 1초(고정) 스턴',
      abilityStart: 5 },
    { id: 'mistilteinn', name: '미스틸테인', tier: '레이드 3단계', blackhammerTier: 2,
      baseStat: [['공격력', 2]],
      ability: '엔지니어가 장착 후 포탑 설치 시 {2}%의 확률로 대포 소환 성공 및 초월 버프가 유지 중일 때 {4}%의 확률로 붉은 터렛 소환, 겜블러가 장착 후 공격 시 7%(고정) 확률로 {111} 추가 데미지',
      abilityStart: 5 },
    { id: 'laevateinn', name: '레바테인', tier: '레이드 3단계', blackhammerTier: 2,
      baseStat: [['크리티컬확률', 1, '%'], ['공격속도', 1, '%']],
      ability: '공격 시 {1}% 확률로 적 일시 빙결, 위자드가 장착 시 아이스랜스의 빙결시간 {0.3}초 증가',
      abilityStart: 5 },
    { id: 'varisada', name: '바리사다', tier: '레이드 3단계', blackhammerTier: 3,
      baseStat: [['공격력', 1], ['방어력', 1]],
      ability: '적 공격시 3초(고정)간 적의 공격력 {3}% 감소, 서모너가 장착 후 적 공격 시 3초(고정)간 공격력 {3}% 증가',
      abilityStart: 5 },

    // 레이드 4단계
    { id: 'arondight', name: '아론다이트', tier: '레이드 4단계', blackhammerTier: 3,
      baseStat: [['공격력', 1], ['공격속도', 1, '%']],
      ability: '불의망토와 열화폭렬검의 특수능력 {8}% 상승, 엔지니어가 장착 시 화염방사 데미지 {6}% 증가',
      abilityStart: 5 },
    { id: 'heavenlysword', name: '천총운검', tier: '레이드 4단계', blackhammerTier: 3,
      baseStat: [['공격속도', 2, '%']],
      ability: '드루이드가 장착 시 일반 공격이 자연치유를 {4}% 확률로 발동, 페인터가 장착 시 회복 스킬 범위 {100} 증가',
      abilityStart: 5 },
    { id: 'uicheon', name: '의천검', tier: '레이드 4단계', blackhammerTier: 3,
      baseStat: [['공격력', 3]],
      ability: '정글 몬스터를 쓰러뜨리면 15초(고정)간 공격력 {3}% 증가, 로그가 장착 후 강탈 사용 시 5초(고정)간 공격력 {3}% 상승, 블레이드가 장착 후 블러디 퓨리 사용시 5초(고정)간 공격력 {3}% 상승',
      abilityStart: 5 },
    { id: 'cheongeunsal', name: '천근살', tier: '레이드 4단계', blackhammerTier: 3,
      baseStat: [['공격속도', 1, '%']],
      ability: '아쳐가 장착 시 관통화살과 다중화살에 데미지 {100} 추가, 머스킷티어와 거너가 장착 시 {4}% 확률로 더블샷',
      abilityStart: 5 },
    { id: 'philosopherstone', name: '현자의돌', tier: '레이드 4단계', blackhammerTier: 3,
      baseStat: [['초당체력회복', 3]],
      ability: '프리스트와 드루이드, 바드가 장착 시 부활스킬 확률 {4}% 상승 (최대 100%(고정)), 네크로맨서가 장착 시 초당체력회복 +{10}',
      abilityStart: 5 },

    // 레이드 5단계
    { id: 'magiclamp', name: '요술램프', tier: '레이드 5단계', blackhammerTier: 3,
      baseStat: [['초당실버', 1]],
      ability: '매초당 얻는 실버 총량 {2}% 증가, 바드가 장착 후 스킬 사용 시 {4}실버 획득, 트레이더가 장착 시 보유 실버의 {0.5}%를 데미지에 추가(최대 500(고정))',
      abilityStart: 5 },
    { id: 'pandora', name: '판도라의상자', tier: '레이드 5단계', blackhammerTier: 4,
      baseStat: [['크리티컬확률', 2, '%']],
      ability: '게임 시작시 {100} 경험치와 {200} 실버를 얻고 시작',
      abilityStart: 5 },
    { id: 'caduceus', name: '카두케우스', tier: '레이드 5단계', blackhammerTier: 4,
      baseStat: [['크리티컬확률', 2.5, '%']],
      ability: '공격력 +{4}, 매지션, 텔레포터가 장착 후 스킬 시전 시 {0.1}초간 무적',
      abilityStart: 5 },
    { id: 'bashoufan', name: '파초선', tier: '레이드 5단계', blackhammerTier: 4,
      baseStat: [['공격력', 2]],
      ability: '프리스트가 장착 시 토네이도의 유지시간 {15}% 증가',
      abilityStart: 5 },
    { id: 'akashicrecord', name: '아카식레코드', tier: '레이드 5단계', blackhammerTier: 4,
      baseStat: [['경험치획득률', 3, '%']],
      ability: '공격력 +{2}, 방어력 +{2}, 체력회복력 +{2}, 체력 +{50}, 위자드가 장착 시 최대마나 {1} 증가',
      abilityStart: 5 },

    // 레이드 6단계
    { id: 'ascalon', name: '아스칼론', tier: '레이드 6단계', blackhammerTier: 5,
      baseStat: [['공격력', 3]],
      ability: '보스 몬스터에게 {3}%의 데미지를 추가, 겜블러가 장착 시 1.5배(고정) 적용',
      abilityStart: 5 },
    { id: 'thothbook', name: '토트의서', tier: '레이드 6단계', blackhammerTier: 5,
      baseStat: [['시작경험치', 50]],
      ability: '드루이드, 파이터, 랜서, 트레이더, 팔라딘이 장착 후 스킬 사용 시 최대체력 +{10}(최대 10000(고정))',
      abilityStart: 5 },
    { id: 'excalibur', name: '엑스칼리버', tier: '레이드 6단계', blackhammerTier: 5,
      baseStat: [['공격력', 2]],
      ability: '나이트, 쉐프, 로그, 사무라이가 장착 후 공격 시 {2}% 확률로 검격, 피격 시 {0.5}% 확률로 피해 무시(한손검 전용)',
      abilityStart: 5 },
    { id: 'solomonring', name: '솔로몬의반지', tier: '레이드 6단계', blackhammerTier: 5,
      baseStat: [['흡혈', 0.5, '%']],
      ability: '네크로맨서가 장착 시 매 {5/-0.5}초마다 전방으로 해골 {1/1/2/2/3}기 소환, 해골 소환 시 체력 100(고정) 회복',
      abilityStart: 5, customAbility: 'solomonring' },
    { id: 'imperialjade', name: '전국옥새', tier: '레이드 6단계', blackhammerTier: 5,
      baseStat: [['체력', 50]],
      ability: '전 아군에게 적용되는 공격력 15%(고정) 버프 토템을 성에 설치하고 {30/-5}초마다 5초(고정)간 버프 부여(다수 보유 시 1%(고정)씩 증가)',
      abilityStart: 5, customAbility: 'imperialjade' },

    // 레이드 7단계
    { id: 'gungnir', name: '궁니르', tier: '레이드 7단계', blackhammerTier: 6,
      baseStat: [['공격속도', 2, '%']],
      ability: '원거리 영웅이 열화폭렬검 장착 시 일반공격에 폭발 확률 {4}% 부여',
      abilityStart: 5 },
    { id: 'brancauldron', name: '브란의가마솥', tier: '레이드 7단계', blackhammerTier: 6,
      baseStat: [['부활시간감소', 1, '%']],
      ability: '체력이 30%(고정) 이하일 때 즉시 체력 전체 회복({95/-15}초 쿨다운), 피에로가 장착 시 방어력 {20} 추가 상승',
      abilityStart: 5, customAbility: 'brancauldron' },
    { id: 'ankh', name: '앙크', tier: '레이드 7단계', blackhammerTier: 6,
      baseStat: [['체력', 100]],
      ability: '근접영웅이 피격 시 체력을 {12} 회복(근접 전용), 피에로가 장착 후 피격 시 [코메디] 포인트 {5}% 추가 증가, 서모너가 장착시 서모너 소드 충전속도가 {5}% 감소',
      abilityStart: 5 },
    { id: 'trident', name: '삼지창', tier: '레이드 7단계', blackhammerTier: 6,
      baseStat: [['크리티컬확률', 1, '%'], ['공격력', 2]],
      ability: '쉐프와 랜서, 로그, 파이터의 일반 공격 사거리 {10}% 증가 및 적군 {1/1/2/2/3}기 다중 타격',
      abilityStart: 5, customAbility: 'trident' },
    { id: 'goldenapple', name: '황금사과', tier: '레이드 7단계', blackhammerTier: null,
      baseStat: [],
      ability: '클리어 경험치 보상 {1}% 상승(장착 무관하며 보유 시 발동)',
      abilityStart: 1 },

    // 레이드 8단계
    { id: 'ganjangmakya', name: '간장막야', tier: '레이드 8단계', blackhammerTier: 6,
      baseStat: [['공격력', 2]],
      ability: '버서커, 쉐프, 파이터가 장착 후 크리티컬 공격 시 {5}% 확률로 150%(고정)데미지의 슈퍼크리티컬 발동',
      abilityStart: 5 },
    { id: 'dainsleif', name: '다인슬라이프', tier: '레이드 8단계', blackhammerTier: 6,
      baseStat: [['공격력', 1], ['체력', 30]],
      ability: '몬스터 처치 시 체력을 {10} 회복하고 체력이 최대치인 경우 그 절반의 최대체력 증가 (최대 5000(고정))',
      abilityStart: 5 },
    { id: 'ssangryonggeom', name: '쌍룡검', tier: '레이드 8단계', blackhammerTier: 6,
      baseStat: [['공격속도', 2, '%']],
      ability: '성 내부에 있으면 공격력 {8}% 상승 (디펜스만 해당)',
      abilityStart: 5 },
    { id: 'yonggwanggeom', name: '용광검', tier: '레이드 8단계', blackhammerTier: 7,
      baseStat: [['공격력', 1]],
      ability: '전체 체력 증가 +{4}%',
      abilityStart: 5 },
    { id: 'chandrahas', name: '찬드라하스', tier: '레이드 8단계', blackhammerTier: 7,
      baseStat: [['체력', 100]],
      ability: '위치가 장착 후 공격 시 전방으로 공격력의 {6}%의 달의 칼날 발사 (최대 2타(고정))',
      abilityStart: 5 },

    // 레이드 9단계
    { id: 'cheonggang', name: '청강검', tier: '레이드 9단계', blackhammerTier: 7,
      baseStat: [['웨이브실버보상', 40]],
      ability: '좌우측 라인 중 한곳에 혼자 있을 경우 공격속도 증가 {10}% (디펜스만 해당)',
      abilityStart: 5 },
    { id: 'tyrfing', name: '티르빙', tier: '레이드 9단계', blackhammerTier: 7,
      baseStat: [['체력', -4, '%'], ['초당체력회복', -1]],
      ability: '스킬 데미지 증가 {4}%',
      abilityStart: 1 },
    { id: 'gaebolg', name: '게볼그', tier: '레이드 9단계', blackhammerTier: 7,
      baseStat: [['크리티컬확률', 1, '%']],
      ability: '랜서가 장착 시 모든 스킬 데미지 {6}% 증가',
      abilityStart: 5 },
    { id: 'bangcheonhwageuk', name: '방천화극', tier: '레이드 9단계', blackhammerTier: 7,
      baseStat: [['이동속도', 1, '%']],
      ability: '적을 쓰러뜨리면 근접한 다른 적에게 공격력의 {20}% 데미지, 서모너가 장착 시 기본 공격 범위 {10}% 증가',
      abilityStart: 5 },
    { id: 'bangobu', name: '반고부', tier: '레이드 9단계', blackhammerTier: 7,
      baseStat: [['체력', 50]],
      ability: '공격 시 적에게 영구적으로 추가 데미지를 입히는 갑옷 파괴를 {2} 부여 (최대 1000(고정)) (디펜스, 주간보스만 해당)',
      abilityStart: 5 },

    // 레이드 10단계
    { id: 'sarunga', name: '사릉가', tier: '레이드 10단계', blackhammerTier: 8,
      baseStat: [['공격속도', 2, '%']],
      ability: '하늘에서 2초(고정)당 1개의 화살비 소환, {40}%(고정) 데미지',
      abilityStart: 5 },
    { id: 'erosarrow', name: '에로스의화살', tier: '레이드 10단계', blackhammerTier: 8,
      baseStat: [['시작경험치', 50]],
      ability: '위치, 바드, 페인터가 장착 후 적을 공격 시 {10}% 확률로 적을 3초(고정)간 매혹(보스 제외)',
      abilityStart: 5 },
    { id: 'tahlum', name: '타흘룸', tier: '레이드 10단계', blackhammerTier: 8,
      baseStat: [['공격력', 1]],
      ability: '머스킷티어와 거너, 메카닉이 장착 시 전방의 적을 2초(고정)마다 1회 자동 공격 (누적 {70/+10}%)',
      abilityStart: 5, customAbility: 'tahlum' },
    { id: 'bulrocho', name: '불로초', tier: '레이드 10단계', blackhammerTier: 8,
      baseStat: [['부활시간감소', 2, '%']],
      ability: '특성 무적 지속시간 {1}초 추가, 특성 부활 발동 확률 {1}% 증가',
      abilityStart: 5 },
    { id: 'necronomicon', name: '네크로노미콘', tier: '레이드 10단계', blackhammerTier: 8,
      baseStat: [['초당체력회복', -5]],
      ability: '죽을때마다 체력 {50} 증가, 데미지 {5} 증가 (최대 10회(고정))',
      abilityStart: 5 },

    // 레이드 11단계
    { id: 'bookofthedead', name: '사자의서', tier: '레이드 11단계', blackhammerTier: 8,
      baseStat: [['경험치획득률', 1, '%']],
      ability: '수정체력 +{5000}, 수정 데미지 경감 {1}%',
      abilityStart: 5 },
    { id: 'talaria', name: '탈라리아', tier: '레이드 11단계', blackhammerTier: 8,
      baseStat: [['공격속도', 1, '%'], ['이동속도', 0.5, '%']],
      ability: '{3/+1}단 점프, 점프 횟수마다 3%(고정)씩 3초(고정)간 공격력 버프 획득, 메카닉 레이저 쿨타임 {1}초 감소',
      abilityStart: 5, customAbility: 'talaria' },
    { id: 'golem', name: '골렘', tier: '레이드 11단계', blackhammerTier: 8,
      baseStat: [['시작실버', 100]],
      ability: '{125}% 공격력의 골렘을 수정 근처에 소환',
      abilityStart: 5 },

    // 레이드 12단계
    { id: 'oracle', name: '오라클', tier: '레이드 12단계', blackhammerTier: null,
      baseStat: [],
      ability: '쌓인 실버량 1000(고정) 마다 공격력 추가 +{3/+1} (최대 공격력 {60/+5}, 장착 무관하며 보유 시 발동)',
      abilityStart: 1, customAbility: 'oracle' },
    { id: 'bindheart', name: '바인드하트', tier: '레이드 12단계', blackhammerTier: null,
      baseStat: [],
      ability: '주간보스 보상량 {3}% 증가 (장착 무관하며 보유 시 발동)',
      abilityStart: 1 },
    { id: 'etherion', name: '에테리온', tier: '레이드 12단계', blackhammerTier: null,
      baseStat: [],
      ability: '유물 강화 시 에테르를 재료로 해서 강화 실패하는 경우 에테르를 {3}%만큼 복구 (장착 무관, 보유 시 발동)',
      abilityStart: 1 },

    // 레이드 13단계
    { id: 'spiritblessing', name: '정령의 축복', tier: '레이드 13단계', blackhammerTier: null,
      baseStat: [],
      ability: '디펜스 {3}단계까지 난이도 비례 클리어 경험치 상승 1%(고정), 초기 실버 1%(고정) (장비 무관하게 적용, 최대 난이도 {3}까지 적용)',
      abilityStart: 1 },
    { id: 'silverhunter', name: '실버헌터', tier: '레이드 13단계', blackhammerTier: null,
      baseStat: [],
      ability: '1초(고정)간 움직임 지속 시 은화 +{34/+2} (장착무관, 최대 {2000/+1000}), 5초마다 공격력의 20%(고정) 폭탄 생성, 공격력은 보유 은화 {900/-50}당 +1%(고정) (최대 +20%(고정))',
      abilityStart: 1, customAbility: 'silverhunter' },

    // 방탈출
    { id: 'ambrosia', name: '암브로시아', tier: '방탈출', blackhammerTier: 4,
      baseStat: [['체력', 30], ['부활시간', -1, '%']],
      ability: '레벨의 {700}% 만큼 전체 체력 증가, 피에로, 바드, 텔레포터 장착 시 체력 {150} 증가',
      abilityStart: 5 },
    { id: 'ankila', name: '앙킬라', tier: '방탈출', blackhammerTier: 4,
      baseStat: [['방어력', 2], ['체력', 20]],
      ability: '피격 시 레벨의 {100}% 만큼 데미지를 감소시키고 3초(고정)간 공격력 {1}% 상승',
      abilityStart: 5 },
    { id: 'nemealion', name: '네메아사자가죽', tier: '방탈출', blackhammerTier: 4,
      baseStat: [['체력', 50]],
      ability: '전체 체력의 1/3 이상 데미지를 받으면 데미지를 받기 직전 3초(고정)간 방어력 {30} 상승(쿨다운 12초(고정)), 비스트가 장착 시 누적체력 {1000} 증가',
      abilityStart: 5 },
    { id: 'ajaxshield', name: '아이아스의방패', tier: '방탈출', blackhammerTier: 5,
      baseStat: [['방어력', 1]],
      ability: '적의 공격을 {1}회 막는 방벽 생성(쿨타임 80초(고정)), 가디언, 팔라딘 2배 적용',
      abilityStart: 3, customAbility: 'ajaxshield' },
    { id: 'heavenlybelt', name: '천사옥대', tier: '방탈출', blackhammerTier: 4,
      baseStat: [['방어력', 3]],
      ability: '피격 시 받는 모든 데미지를 {1.5}% 감소시키고 전체 체력보다 큰 데미지는 {5}% 확률로 회피',
      abilityStart: 5 },

    // 소환
    { id: 'blackhammer', name: '블랙해머', tier: '소환', blackhammerTier: null,
      baseStat: [],
      ability: '다른 유물들의 특수능력을 +1강 증가시킴',
      abilityStart: 1, customAbility: 'blackhammer' },
    { id: 'blueprint', name: '성지키기설계도', tier: '소환', blackhammerTier: null,
      baseStat: [],
      ability: '다이아 보상 {1}% 증가',
      abilityStart: 1, customAbility: 'blueprint' },
    { id: 'goldenduck', name: '황금알오리', tier: '소환', blackhammerTier: null,
      baseStat: [],
      ability: '디펜스 모드(난이도 11(고정) 이상) 게임 클리어 시 골드 보상 +1 (하루 최대 {40/+20}개, 장착 무관하며 보유 시 발동)',
      abilityStart: 1, customAbility: 'goldenduck' },
    { id: 'arkofcovenant', name: '언약궤', tier: '소환', blackhammerTier: null,
      baseStat: [],
      ability: '영웅 초월 액티브 스킬의 쿨타임 {1}% 감소 (장착 무관하며 보유 시 발동)',
      abilityStart: 1 },
    { id: 'heropentagon', name: '영웅의 펜타곤', tier: '소환', blackhammerTier: null,
      baseStat: [],
      ability: '(레이드 및 주간보스 한정) 내 영웅의 공격력 +{2/+1}% 증가, 피격 시 {0.6/+0.3}% 확률로 1회(고정) 보호막 생성 (장착 무관, 보유 시 자동 발동)',
      abilityStart: 1, customAbility: 'heropentagon' },
    { id: 'transcendbook', name: '초월의 서', tier: '소환', blackhammerTier: null,
      baseStat: [],
      ability: '출석체크 시 초월석 {10/+5}개 추가 지급, 레이드에서 획득 가능한 초월석 +{10/+5} (장착 무관, 보유 시 자동 발동)',
      abilityStart: 1, customAbility: 'transcendbook' },
];

// 티어 순서
const TIER_ORDER = [
    '레이드 1단계', '레이드 2단계', '레이드 3단계', '레이드 4단계', '레이드 5단계',
    '레이드 6단계', '레이드 7단계', '레이드 8단계', '레이드 9단계', '레이드 10단계',
    '레이드 11단계', '레이드 12단계', '레이드 13단계', '방탈출', '소환'
];

// 블랙해머 적용 유물 목록
const BLACKHAMMER_TIERS = {
    1: ['아이기스', '아킬레우스갑주', '듀랜달', '페일노트', '묠니르', '힐데그림', '청룡언월도'],
    2: ['여의봉', '칼라드블그', '다이츠렌', '갈라틴', '매화검', '미스틸테인', '레바테인'],
    3: ['바리사다', '아론다이트', '천총운검', '의천검', '천근살', '현자의돌', '요술램프'],
    4: ['판도라의상자', '카두케우스', '파초선', '아카식레코드', '암브로시아', '앙킬라', '네메아사자가죽'],
    5: ['아이아스의방패', '천사옥대', '아스칼론', '토트의서', '엑스칼리버', '솔로몬의반지', '전국옥새'],
    6: ['궁니르', '브란의가마솥', '앙크', '삼지창', '간장막야', '다인슬라이프', '쌍룡검'],
    7: ['용광검', '찬드라하스', '청강검', '티르빙', '게볼그', '방천화극', '반고부'],
    8: ['사릉가', '에로스의화살', '타흘룸', '불로초', '네크로노미콘', '사자의서', '탈라리아', '골렘']
};
